### ISSUE TITLE
Unable to load gltf model in Aframe with Angular 7 

### ISSUE THREAD

**Issue by nirajupadhyay11** [brakmic/Angular-VR-Starter#8]
Hi,

I am trying to load a gltf-model using aframe 0.9.0 and Angular 7. I am able to display primitives such as "a-box" but the gltf model does not load.  Here is my code - 

```
<a-scene embedded="" cursor="rayOrigin: mouse">
  <a-assets>
   <!-- <a-asset-item id="bedroom" src="../../assets/models/homedesign/scene.gltf"></a-asset-item> -->
   <a-asset-item id="bedroom" src="https://cx20.github.io/gltf-test/examples/threejs/index.html?category=sampleModels&model=Duck&scale=1&type=glTF-Embedded"></a-asset-item>
  </a-assets>

   <a-entity id="camera" camera="" position="0 0 0" look-controls wasd-controls>
   </a-entity>        

  <a-entity id="room" gltf-model="#bedroom" position="0 0 -12" rotation= "0 160 0" material-map="map: map">
  </a-entity> 
  <a-box position="0 1 -3" color="red"></a-box>

</a-scene>
```
I have double checked the paths and it seems to be correct. All I can see if the red box. 

The message in the console says core:propertyTypes:warn "#bedroom" asset not found.

Could you kindly take a look? I have also posted this on stackoverflow - https://stackoverflow.com/questions/55077356/aframe-angular-7-unable-to-load-gltf-model

Thanks so much

**Comment by brakmic** [comment]
GitHug is a developer community, not a support box! DO NOT misuse the Issues tab.
